packages:
  - cinefy-management
  - cinefy-ui
  - cinefy-client
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - "@lucide/angular@1.18.0"
