packages:
  - cinefy-management
  - cinefy-ui
  - cinefy-client
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - "@lucide/angular@1.43.0"
  - "@angular/cdk@22.1.6"
  - "primeng@22.1.1"
