spring.application.name=Cinefy

# Common JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Auditing Configuration
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.org.hibernate.envers.global_with_modified_flag=true
spring.jpa.properties.org.hibernate.envers.revision_field_name=REVISION_ID
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=REVISION_TYPE
spring.jpa.properties.org.hibernate.envers.modified_flag_suffix=_MODIFIED
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_REVISIONS